# Generated by Django 5.2 on 2025-04-11 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(protocol='IPV4')),
                ('server_hostname', models.CharField(max_length=100)),
                ('server_environment', models.CharField(choices=[('PROD', 'Produccion'), ('DEV', 'Desarrollo'), ('TEST', 'Pruebas')], max_length=10)),
                ('server_status', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'Mantenimiento'), ('sin uso', 'Retirado')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server_os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servers.os')),
            ],
        ),
    ]
