# Generated by Django 5.2 on 2025-04-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='os_img',
            field=models.ImageField(null=True, upload_to='os'),
        ),
    ]
