# Generated by Django 5.2 on 2025-04-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_os_os_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.CharField(blank=True, choices=[('WEB', 'Servidor Web'), ('DB', 'Servidor de Base de Datos'), ('APP', 'Servidor de Aplicaciones'), ('DNS', 'Servidor DNS'), ('FTP', 'Servidor FTP'), ('SMTP', 'Servidor de Correo'), ('FILES', 'Servidor de Archivos'), ('PROXY', 'Servidor Proxy'), ('OTHER', 'Otro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='os',
            name='os_img',
            field=models.ImageField(blank=True, null=True, upload_to='os'),
        ),
    ]
