# Generated by Django 5.2 on 2025-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_server_server_type_alter_os_os_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='os_type',
            field=models.CharField(blank=True, choices=[('Linux', 'Linux'), ('Windows', 'Windows')], max_length=30, null=True),
        ),
    ]
