# Generated by Django 5.2 on 2025-04-11 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ip', models.GenericIPAddressField(protocol='IPV4')),
                ('tipo', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo'), ('nube', 'Nube')], default='interno', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DNSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=255)),
                ('entry_type', models.CharField(choices=[('A', 'A - Dirección IPv4'), ('AAAA', 'AAAA - Dirección IPv6'), ('PTR', 'PTR - Reversa'), ('CNAME', 'CNAME - Alias'), ('MX', 'MX - Mail Exchange'), ('TXT', 'TXT - Texto'), ('NS', 'NS - Nameserver')], max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dns_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='dns.dns')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_dns', to='servers.server')),
            ],
        ),
    ]
